// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5xRYVJVfe6usiUxSSk6qRKF59t54ThOY',
    appId: '1:273061431372:web:6636f55c2eac18cbd00ce9',
    messagingSenderId: '273061431372',
    projectId: 'recipe-app-17dab',
    authDomain: 'recipe-app-17dab.firebaseapp.com',
    storageBucket: 'recipe-app-17dab.appspot.com',
    measurementId: 'G-WQSEVQT53V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleWoNO4VjfnaEeFUtzmJExoc_VD8OnPU',
    appId: '1:273061431372:android:5537150dac8d4868d00ce9',
    messagingSenderId: '273061431372',
    projectId: 'recipe-app-17dab',
    storageBucket: 'recipe-app-17dab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAyLETSPi273EHgly_MBytYwebXp9fMdI',
    appId: '1:273061431372:ios:9fc4bafa3295b9a6d00ce9',
    messagingSenderId: '273061431372',
    projectId: 'recipe-app-17dab',
    storageBucket: 'recipe-app-17dab.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAyLETSPi273EHgly_MBytYwebXp9fMdI',
    appId: '1:273061431372:ios:c427de5773c11812d00ce9',
    messagingSenderId: '273061431372',
    projectId: 'recipe-app-17dab',
    storageBucket: 'recipe-app-17dab.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
